# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadStart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 1080)
        MainWindow.setMaximumSize(QtCore.QSize(1217, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 30, 931, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(3, 1, 931, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(5, 146, 922, 191))
        self.frame_2.setMinimumSize(QtCore.QSize(922, 191))
        self.frame_2.setMaximumSize(QtCore.QSize(922, 191))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"\n"
"\n"
"background:rgb(234, 234, 234);\n"
"border-radius:15px;\n"
"border:none\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(690, 110, 111, 61))
        self.stackedWidget_2.setStyleSheet("background:rgba(0,0,0,0);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background:rgb(172, 32, 32);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton.setIconSize(QtCore.QSize(31, 31))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"\n"
"background:rgb(21, 29, 75);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton_3:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setIconSize(QtCore.QSize(31, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_12)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"\n"
"background:rgb(57, 60, 255);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton_6:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setIconSize(QtCore.QSize(31, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget_2.addWidget(self.page_12)
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_3.setGeometry(QtCore.QRect(790, 110, 101, 61))
        self.stackedWidget_3.setStyleSheet("background:rgba(0,0,0,0);")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"\n"
"background:rgb(42, 79, 163);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setIconSize(QtCore.QSize(24, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"\n"
"background:rgb(57, 60, 255);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton_5:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setIconSize(QtCore.QSize(24, 26))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget_3.addWidget(self.page_11)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"\n"
"background:rgb(57, 60, 255);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton_4:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setIconSize(QtCore.QSize(24, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget_3.addWidget(self.page_6)
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_4.setGeometry(QtCore.QRect(30, 10, 671, 80))
        self.stackedWidget_4.setStyleSheet("background:rgba(0,0,0,0);")
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_5 = QtWidgets.QLabel(self.page_7)
        self.label_5.setGeometry(QtCore.QRect(380, 47, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-size:13px;\n"
"color:rgb(120, 120, 120);\n"
"border:none;")
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.page_7)
        self.label_11.setGeometry(QtCore.QRect(70, 47, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("font-size:13px;\n"
"color:rgb(120, 120, 120);\n"
"border:none;")
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.page_7)
        self.label_10.setGeometry(QtCore.QRect(12, 45, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font-size:15px;\n"
"color:rgb(120, 120, 120);\n"
"border:none;\n"
"font-weight:bold")
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.page_7)
        self.label_3.setGeometry(QtCore.QRect(10, 9, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size:25px;\n"
"color:rgb(107, 107, 107);\n"
"border:none;")
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setGeometry(QtCore.QRect(310, 46, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font-size:15px;\n"
"color:rgb(120, 120, 120);\n"
"border:none;\n"
"font-weight:bold")
        self.label_9.setObjectName("label_9")
        self.stackedWidget_4.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.label_7 = QtWidgets.QLabel(self.page_8)
        self.label_7.setGeometry(QtCore.QRect(220, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font-size:25px;\n"
"color:rgb(107, 107, 107);\n"
"border:none;")
        self.label_7.setObjectName("label_7")
        self.stackedWidget_4.addWidget(self.page_8)
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_5.setGeometry(QtCore.QRect(90, 95, 551, 71))
        self.stackedWidget_5.setStyleSheet("#stackedWidget_5 {\n"
"background:rgb(240, 240, 240);\n"
"border-radius:15px;\n"
"\n"
"}")
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_6 = QtWidgets.QLabel(self.page_9)
        self.label_6.setGeometry(QtCore.QRect(89, 21, 231, 16))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-size:13px;\n"
"color:rgb(107, 107, 107);\n"
"border:none;")
        self.label_6.setObjectName("label_6")
        self.progressBar = QtWidgets.QProgressBar(self.page_9)
        self.progressBar.setGeometry(QtCore.QRect(19, 48, 499, 4))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("border:1px solid black")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.page_9)
        self.label_4.setGeometry(QtCore.QRect(30, 19, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-size:15px;\n"
"color:rgb(107, 107, 107);\n"
"border:none;\n"
"font-weight:bold")
        self.label_4.setObjectName("label_4")
        self.stackedWidget_5.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_8 = QtWidgets.QLabel(self.page_10)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(-1)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font-size:25px;\n"
"color:rgb(107, 107, 107);\n"
"border:none;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.stackedWidget_5.addWidget(self.page_10)
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setGeometry(QtCore.QRect(105, 2, 481, 141))
        self.frame_10.setStyleSheet("#frame_10 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;\n"
"background:rgb(232, 232, 232);\n"
"color:rgb(197, 197, 197);\n"
"}\n"
"#frame_8:hover{\n"
"background:qlineargradient(spread:reflect, x1:0.972, y1:0.188, x2:0.255545, y2:0.665, stop:0 rgba(0, 0, 0, 206), stop:1 rgba(156, 156, 156, 168));\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setGeometry(QtCore.QRect(20, 30, 441, 80))
        self.frame_15.setStyleSheet("background:rgb(242, 242, 242);\n"
"border-radius:15px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_18 = QtWidgets.QLabel(self.frame_15)
        self.label_18.setGeometry(QtCore.QRect(0, 24, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(17)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("\n"
"color:rgb(104, 104, 104);\n"
"background:rgba(0,0,0,0);\n"
"padding-left:5px;\n"
"padding-bottom:3px")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setGeometry(QtCore.QRect(345, 340, 531, 141))
        self.frame_11.setStyleSheet("#frame_11 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"font-size:20px;\n"
"\n"
"border-bottom-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"background:rgb(232, 232, 232);\n"
"color:rgb(197, 197, 197);\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        self.frame_16.setGeometry(QtCore.QRect(40, 30, 441, 80))
        self.frame_16.setStyleSheet("background:rgb(242, 242, 242);\n"
"border-radius:15px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_19 = QtWidgets.QLabel(self.frame_16)
        self.label_19.setGeometry(QtCore.QRect(0, 27, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(17)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("\n"
"color:rgb(104, 104, 104);\n"
"background:rgba(0,0,0,0);\n"
"padding-left:5px;\n"
"padding-bottom:3px")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(0)
        self.stackedWidget_5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Cancle"))
        self.pushButton_3.setText(_translate("MainWindow", "done"))
        self.pushButton_6.setText(_translate("MainWindow", "close"))
        self.pushButton_2.setText(_translate("MainWindow", "Pause"))
        self.pushButton_5.setText(_translate("MainWindow", "Retry"))
        self.pushButton_4.setText(_translate("MainWindow", "Open"))
        self.label_5.setText(_translate("MainWindow", "Query"))
        self.label_11.setText(_translate("MainWindow", "www.sarzamindownload.com"))
        self.label_10.setText(_translate("MainWindow", "Host"))
        self.label_3.setText(_translate("MainWindow", "Operation started "))
        self.label_9.setText(_translate("MainWindow", "Query"))
        self.label_7.setText(_translate("MainWindow", "Just a moment . . ."))
        self.label_6.setText(_translate("MainWindow", "Taking care of security measures . . ."))
        self.label_4.setText(_translate("MainWindow", "Status"))
        self.label_8.setText(_translate("MainWindow", "Extracting . . ."))
        self.label_18.setText(_translate("MainWindow", "The process has been started"))
        self.label_19.setText(_translate("MainWindow", "We will handle everything"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
