# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(130, 50, 331, 291))
        self.frame.setMinimumSize(QtCore.QSize(331, 291))
        self.frame.setMaximumSize(QtCore.QSize(331, 291))
        self.frame.setStyleSheet("background:rgb(235, 235, 235);\n"
"\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("#pushButton_7 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"\n"
"border-radius:15px;\n"
"background:rgb(241, 241, 241);\n"
"color:rgb(167, 167, 167);\n"
"\n"
"}\n"
"\n"
"\n"
"#pushButton_7:hover {\n"
"color:rgb(206, 206, 206);\n"
"background:rgb(240, 240, 240);\n"
"font-weight:bold;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 220, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("#pushButton_8 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"\n"
"border-radius:15px;\n"
"background:rgb(38, 38, 38);\n"
"color:rgb(167, 167, 167);\n"
"\n"
"}\n"
"\n"
"\n"
"#pushButton_8:hover {\n"
"color:rgb(206, 206, 206);\n"
"background:rgb(240, 240, 240);\n"
"font-weight:bold;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 20, 271, 161))
        self.frame_2.setStyleSheet("background:rgb(241, 241, 241);\n"
"\n"
"border-radius:15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("\n"
"color:rgb(104, 104, 104);\n"
"background:rgba(0,0,0,0);\n"
"padding-left:5px;\n"
"padding-bottom:3px;\n"
"font-weight:bold;")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(0, 40, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(12)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("\n"
"color:rgb(104, 104, 104);\n"
"background:rgba(0,0,0,0);\n"
"padding-left:5px;\n"
"padding-bottom:3px")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Install"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete"))
        self.label_19.setText(_translate("MainWindow", "Kmplayer"))
        self.label_20.setText(_translate("MainWindow", "www.sarzamindonwload.com"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
