# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtOptionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameToAdd = QtWidgets.QFrame(self.centralwidget)
        self.frameToAdd.setGeometry(QtCore.QRect(60, 70, 475, 121))
        self.frameToAdd.setMinimumSize(QtCore.QSize(475, 121))
        self.frameToAdd.setMaximumSize(QtCore.QSize(475, 121))
        self.frameToAdd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToAdd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToAdd.setObjectName("frameToAdd")
        self.frame = QtWidgets.QFrame(self.frameToAdd)
        self.frame.setGeometry(QtCore.QRect(7, 0, 461, 111))
        self.frame.setMinimumSize(QtCore.QSize(371, 111))
        self.frame.setStyleSheet("background:rgb(250, 250, 250);\n"
"border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 9, 381, 36))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(99, 99, 99);\n"
"border:none;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(330, 60, 111, 37))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background:rgb(161, 0, 0);\n"
"border:1px solid rgb(234, 234, 234);\n"
"color:rgb(244, 244, 244);\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"background:rgb(255, 255, 255);\n"
"}")
        self.pushButton.setIconSize(QtCore.QSize(21, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(19, 9, 51, 36))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color:rgb(99, 99, 99);\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "64 bit"))
        self.pushButton.setText(_translate("MainWindow", "get"))
        self.label_2.setText(_translate("MainWindow", "info:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
