# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1071)
        font = QtGui.QFont()
        font.setFamily("Raleway Thin Medium")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/* HORIZONTAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(240, 240, 240);\n"
"    height: 15px;\n"
"    margin: 0 15px 0 15px;\n"
"    width:15px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"/* HANDLE BAR HORIZONTAL */\n"
"QScrollBar::handle:horizontal {  \n"
"    background: rgba(240, 240, 240,.2);\n"
"    min-width: 10px;\n"
"    max_width:15px;\n"
"    width:15px;\n"
"    border-radius: 7px;\n"
"    height:1px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{  \n"
"    background-color: rgba(240, 240, 240,.3);\n"
"    height:1px\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {  \n"
"    background-color: rgba(240, 240, 240,.4);\n"
"}\n"
"\n"
"/* BTN LEFT - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: nonergb(11, 11, 11);\n"
"    background-color: rgba(0,0,0,0);\n"
"    width: 15px;\n"
"    height:10px !important;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {  \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {  \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN RIGHT - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgba(59, 59, 90,0);\n"
"    width: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {  \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {  \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-2, -4, 1681, 843))
        self.frame.setStyleSheet("#frame {\n"
"background:rgba(0,0,0,0)\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(1470, 3, 41, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"\n"
"background:rgba(153, 153, 153,0);\n"
"border:none;\n"
"outline:none\n"
"    \n"
"}\n"
"\n"
"\n"
"#pushButton_2:hover {\n"
"background:rgba(203, 0, 0, .6);\n"
"\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("close_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(43, 43))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background:rgba(153, 153, 153,0);\n"
"border:none;\n"
"outline:none\n"
"    \n"
"}\n"
"\n"
"\n"
"#pushButton:hover {\n"
"background:rgba(255, 255, 255, .5);\n"
"\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow_back_ios_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget_3.setGeometry(QtCore.QRect(440, 50, 1141, 611))
        self.stackedWidget_3.setStyleSheet("background:rgba(0,0,0,0)")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page_6)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 1081, 611))
        self.scrollArea.setStyleSheet("\n"
"background:rgba(0,0,0,0);\n"
"border:none\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1081, 611))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget_3.addWidget(self.page_6)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(550, 10, 921, 171))
        self.stackedWidget.setStyleSheet("#stackedWidget {\n"
"background:rgba(0,0,0,0);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 861, 45))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"background:rgb(235, 235, 235);\n"
"border-radius:15px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setGeometry(QtCore.QRect(250, 8, 411, 30))
        self.frame_11.setStyleSheet("#frame_11 {\n"
"background:rgb(220, 220, 220);\n"
"border-radius:15px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border:none;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setGeometry(QtCore.QRect(27, -2, 361, 29))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("#lineEdit {\n"
"background:rgba(0,0,0,0);\n"
"border:none;\n"
"\n"
"color:rgb(85, 85, 85);\n"
"\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 8, 181, 30))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"\n"
"border-radius:15px;\n"
"background:rgb(241, 241, 241);\n"
"color:rgb(167, 167, 167);\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"\n"
"}\n"
"\n"
"\n"
"#pushButton_3:hover {\n"
"color:rgb(206, 206, 206);\n"
"background:rgb(240, 240, 240);\n"
"font-weight:bold;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 8, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("#pushButton_7 {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"\n"
"border-radius:15px;\n"
"background:rgb(241, 241, 241);\n"
"border-bottom-left-radius:0px;\n"
"border-top-left-radius:0px;\n"
"color:rgb(167, 167, 167);\n"
"\n"
"}\n"
"\n"
"\n"
"#pushButton_7:hover {\n"
"color:rgb(206, 206, 206);\n"
"background:rgb(240, 240, 240);\n"
"font-weight:bold;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 9, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Raleway Thin")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("#comboBox {\n"
"\n"
"\n"
"\n"
"border:none;\n"
"\n"
"border-radius:15px;\n"
"background:rgb(43, 43, 43);\n"
"color:rgb(167, 167, 167);\n"
"padding-left:10px;\n"
"outline : none;\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.popUpStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.popUpStack.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.popUpStack.setMaximumSize(QtCore.QSize(1920, 1080))
        self.popUpStack.setStyleSheet("\n"
"\n"
"\n"
"background:rgba(1,1,1,0);")
        self.popUpStack.setObjectName("popUpStack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1340, 820, 571, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-20, 270, 1951, 571))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.popUpStack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.popUpStack.addWidget(self.page_4)
        self.popUpStack.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_3.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.popUpStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type here to search"))
        self.pushButton_3.setText(_translate("MainWindow", "Find"))
        self.pushButton_7.setText(_translate("MainWindow", "History"))
        self.comboBox.setItemText(0, _translate("MainWindow", "sarzmindownload"))
        self.comboBox.setItemText(1, _translate("MainWindow", "yasdl"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
